# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34962ff625a33209d8a5852f44bfe20d7634cee97c5ea101d78859bae831f5489f1df64c275093e1e12bd21a636e6536a3a916c01afe3c9a7ff7df84e22b4690

test:
  secret_key_base: 3326b01a4bee2ebbf1ca0bcab1a892deee07c1ec526857e1eda4d25c717c5d33472fc205083836b2d84e1dd964c33aa37fda0703fbd2403ac9bc0e66008f559e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
